services:
  app:
    container_name: go-api-server-echo-app
    build: .
    depends_on:
      - db
      - adminer
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: "./"
        target: "/home"
    tty: true

  db:
    container_name: go-api-server-echo-db
    image: mysql:5.7.40
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
    command:
      --query_cache_type=0
      --query_cache_limit=0
      --query_cache_size=0
      --innodb_file_per_table=1
      --innodb_buffer_pool_size=128M
      --innodb_log_file_size=30MB
      --max_connections=10
    
  adminer:
    container_name: go-api-server-echo-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
