definitions:
  domains.Album:
    properties:
      artist:
        type: string
      id:
        type: integer
      price:
        type: number
      title:
        type: string
    type: object
info:
  contact: {}
paths:
  /:
    get:
      consumes:
      - '*/*'
      description: Show Hello
      produces:
      - text/plain
      responses:
        "200":
          description: Hello, World!
          schema:
            type: string
      summary: Show Hello
      tags:
      - Basic
  /albums:
    get:
      consumes:
      - '*/*'
      description: getAlbums responds with the list of all albums as JSON.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domains.Album'
            type: array
      summary: Show Albums
      tags:
      - Album
    post:
      consumes:
      - application/json
      description: postAlbums adds an album from JSON received in the request body.
      produces:
      - text/plain
      responses:
        "201":
          description: Accepted
          schema:
            type: string
        "400":
          description: Bad Request
          schema: {}
      summary: Post Album
      tags:
      - Album
  /albums/{id}:
    get:
      consumes:
      - '*/*'
      description: getAlbumByID locates the album whose ID value matches the id parameter
      parameters:
      - description: Album id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domains.Album'
        "404":
          description: Not Found
          schema:
            type: string
      summary: Show Album for id
      tags:
      - Album
  /healthcheck:
    get:
      consumes:
      - '*/*'
      description: Show HealthCheck
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Show HealthCheck
      tags:
      - System
swagger: "2.0"
